name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: "18"
  PYTHON_VERSION: "3.11"
  LAMBDA_FUNCTION_NAME: gsq-geochem-portal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: ./.venv

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Build UI app
        run: |
          npm --prefix geochem-portal-ui ci
          npm --prefix geochem-portal-ui run build

      - name: Copy UI build output to Python app
        run: |
          rm -r geochem_portal/static
          cp -r geochem-portal-ui/dist geochem_portal/static

      - name: Install Python dependencies
        run: poetry install

      - name: Package AWS Lambda artifact
        run: |
          (cd .venv/lib/python3.11/site-packages; zip ../../.././../lambda.zip -r .)
          zip -r lambda.zip -u lambda_function.py geochem_portal

      - name: Upload lambda artifact
        run: aws lambda update-function-code --function-name=${{ env.LAMBDA_FUNCTION_NAME }} --zip-file=fileb://lambda.zip
